program: Vector Set Array main
	g++ -std=c++11 GTUVector.o GTUSet.o GTUArray.o main.o -o program
Vector:
	g++ -std=c++11 -c GTUVector.cpp -o GTUVector.o
Set:
	g++ -std=c++11 -c GTUSet.cpp -o GTUSet.o
Array:
	g++ -std=c++11 -c GTUArray.cpp -o GTUArray.o
main:
	g++ -std=c++11 -c main.cpp -o main.o