program:Eight Board Peg Klotski main
	g++ -std=c++11 Klotski.o PegSolitaire.o EightPuzzle.o BoardGame2D.o hw5main.o -o program
Board:
	g++ -std=c++11 -c BoardGame2D.cpp -o BoardGame2D.o
Peg:
	g++ -std=c++11 -c PegSolitaire.cpp -o PegSolitaire.o
Eight:
	g++ -std=c++11 -c EightPuzzle.cpp -o EightPuzzle.o
Klotski:
	g++ -std=c++11 -c Klotski.cpp -o Klotski.o	
main:
	g++ -std=c++11 -c hw5main.cpp -o hw5main.o